# Generated by Django 4.0.5 on 2023-01-21 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0003_wishitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedlist',
            name='booked_price',
            field=models.IntegerField(null=True),
        ),
    ]
