# Generated by Django 4.0.5 on 2023-01-20 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloginfo',
            name='id',
        ),
        migrations.AlterField(
            model_name='bloginfo',
            name='slug',
            field=models.SlugField(blank=True, primary_key=True, serialize=False),
        ),
    ]
