# Generated by Django 4.0.5 on 2023-01-19 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Superuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad_profile',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
