# Generated by Django 4.0.5 on 2023-01-20 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_order_booked_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='guests',
        ),
        migrations.RemoveField(
            model_name='order',
            name='time',
        ),
    ]
